//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public int C__regstration { get; set; }
        public string FIO { get; set; }
        public int Room { get; set; }
        public System.DateTime Arrival_date { get; set; }
        public System.DateTime Departure_date { get; set; }
    
        public virtual Rooms Rooms { get; set; }
    }
}
