//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hotel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rooms
    {
        public Rooms()
        {
            this.Clients = new HashSet<Clients>();
        }
    
        public int ID_room { get; set; }
        public string Category { get; set; }
        public string Description { get; set; }
        public int Price { get; set; }
        public int C__housemaid { get; set; }
        public string Number { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<Clients> Clients { get; set; }
        public virtual Housemaid Housemaid { get; set; }
    }
}
